### PR TITLE
Fixed missing logos and some typos

### PR DESCRIPTION
**Pull request by boorah**
I've added the missing logos. Another reason why some logos are not visible is because Firefox enables content blocking by default, I was having problems with that so I disabled it before running the project.

### CODE REVIEW

**Comment by akanksha-raghav** [comment]
Have a look at the CA program and COde and grab page one logo in each is missing

**Comment by boorah** [comment]
@akanksha-raghav Thanks for replying. As I mentioned in the above comment, those requests are getting blocked due to content blocking. Which browser are you using? I am using chrome and it is working just fine. Have a look or else I might have to change the icons link

**Comment by akanksha-raghav** [comment]
I am also using chrome. Try changing them.

**Comment by boorah** [comment]
Ok

**Pull request merged**
